{% set name = "botorch" %}
{% set version = "0.6.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/botorch-{{ version }}.tar.gz
  sha256: d62abb6246beedba8898ed2f3a78196178f8e3f02d633e9678e7e734caf8c934

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools <48
    - setuptools_scm
  run:
    - python >=3.7
    - pytorch >=1.9
    - gpytorch >=1.6
    - scipy
    - pyro-ppl
    - multipledispatch

test:
  imports:
    - botorch
    - botorch.acquisition
    - botorch.exceptions
    - botorch.generation
    - botorch.models
    - botorch.optim
    - botorch.posteriors
    - botorch.sampling
    - botorch.test_functions
    - botorch.utils
    - botorch.cross_validation
    - botorch.fit
    - botorch.logging
    - botorch.settings

about:
  home: https://botorch.org
  license: MIT
  license_file: LICENSE
  summary: Bayesian Optimization in PyTorch
  doc_url: https://botorch.org/docs/introduction
  dev_url: https://github.com/pytorch/botorch

  description: |
    BoTorch is a library for Bayesian Optimization built on PyTorch.

extra:
  recipe-maintainers:
    - maclandrol
    - ngam
