{% set python_min = "3.10" %}
{% set name = "botorch" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/botorch-{{ version }}.tar.gz
  sha256: 7c6ca67e086a90a4b99afc4bc66317fc7d1638d644e4ed8f553ea7b125392cb7

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
    - toml
    - wheel
  run:
    - python >={{ python_min }}
    - typing_extensions
    - pyre-extensions
    - gpytorch ==1.14
    - linear_operator ==0.6
    - pytorch >=2.0.1
    - pyro-ppl >=1.8.4
    - scipy
    - multipledispatch
    - threadpoolctl

test:
  imports:
    - botorch
    - botorch.acquisition
    - botorch.exceptions
    - botorch.generation
    - botorch.models
    - botorch.optim
    - botorch.posteriors
    - botorch.sampling
    - botorch.test_functions
    - botorch.utils
    - botorch.cross_validation
    - botorch.fit
    - botorch.logging
    - botorch.settings
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://botorch.org
  license: MIT
  license_file: LICENSE
  summary: Bayesian Optimization in PyTorch
  doc_url: https://botorch.org/docs/introduction
  dev_url: https://github.com/pytorch/botorch

  description: |
    BoTorch is a library for Bayesian Optimization built on PyTorch.

extra:
  recipe-maintainers:
    - maclandrol
    - ngam
    - thewchan
