{% set name = "botorch" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/botorch-{{ version }}.tar.gz
  sha256: 1fc19bfbb897634a20d919b4c3d839de4ffd8fa66d778e570aa690ff822738b5

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools <48
    - setuptools_scm
  run:
    - python >=3.7
    - pytorch >=1.11
    - gpytorch >=1.9.0
    - scipy
    - pyro-ppl >=1.8.2
    - multipledispatch

test:
  imports:
    - botorch
    - botorch.acquisition
    - botorch.exceptions
    - botorch.generation
    - botorch.models
    - botorch.optim
    - botorch.posteriors
    - botorch.sampling
    - botorch.test_functions
    - botorch.utils
    - botorch.cross_validation
    - botorch.fit
    - botorch.logging
    - botorch.settings

about:
  home: https://botorch.org
  license: MIT
  license_file: LICENSE
  summary: Bayesian Optimization in PyTorch
  doc_url: https://botorch.org/docs/introduction
  dev_url: https://github.com/pytorch/botorch

  description: |
    BoTorch is a library for Bayesian Optimization built on PyTorch.

extra:
  recipe-maintainers:
    - maclandrol
    - ngam
